### ISSUE TITLE
support for jquery 1.10.x???

### ISSUE THREAD

**Issue by acheson0410** [asual/jquery-address#181]
Hi, 

I just wonder whether this plugin support for jquery 1.10 or not. If not, will it update to support 1.10 soon?

When I was using jquery 1.10.2 with this plugin, it showed Jquery.address is not defined. But it works fine on jquery 1.9.

Thanks.

Johnny

**Comment by c0d3runn3r** [comment]
I'm seeing the same issue.  Also getting this error in the console (jQuery 1.10.1, jquery-address 1.5)

Uncaught TypeError: Cannot read property 'version' of undefined

**Comment by c0d3runn3r** [comment]
It looks like this is fixed in the source.  If I do a git checkout, things work fine.  It appears to be only broken in 1.5.

**Comment by hpurmann** [comment]
I have the same problem in 1.5. But in 1.6 appears another problem:

``` javascript
Uncaught TypeError: undefined is not a function
```

This line is causing it:

``` javascript
$('a[rel*="address:"]').address();
```

**Comment by bknill** [comment]
hpurmann did you ever find a solution to the above problem?

**Comment by hpurmann** [comment]
Not really good practice but i simply commented out line 140 and live with it :)

``` javascript
// $('a[rel*="address:"]').address();
```

**Comment by bknill** [comment]
Ha.  Thanks!

I managed to fix it by adding the jquery address import to the head of the
html document, where previously I was importing it later on in the load.
This seems to have solved it.

On Fri, Sep 5, 2014 at 9:53 AM, Hendrik Purmann notifications@github.com
wrote:

> Not really good practice but i simply commented out line 140 and live with
> it :)
> 
> $('a[rel*="address:"]').address();
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/asual/jquery-address/issues/181#issuecomment-54550971
> .

## 

_Ben Knill_

_Beek CEO_
_Tel: 022 6586424_

**Comment by vasyahacker** [comment]
http://pupunzi.open-lab.com/2012/08/14/jquery-1-8-and-browser-detection/
good fix
